[project]
name = "energy-meter"
version = "0.1.1"
description = "Energy meter Modbus reader."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pymodbus<=3.8.3",
    "flex-modbus-reader>=0.0.1",
    "pytest>=8.3.4",
]
[tool.black]
line-length = 80
